### ISSUE TITLE
В уведомлениях об оплате счетов не указан параметр bill_id

### ISSUE THREAD

**Issue by danielkanzel** [QIWI-API/pull-payments-docs#2]
![image](https://user-images.githubusercontent.com/26162864/51178641-37371180-18d4-11e9-8196-e692e2f353f9.png)
А в таблице про него нет ни слова

**Comment by Jamaska** [comment]
Спасибо , добавили.

**Comment by danielkanzel** [comment]
![image](https://user-images.githubusercontent.com/26162864/51183923-d283b300-18e3-11e9-8190-dbb20002a85e.png)
Еще тут ссылка битая, но это мелочь
