### ISSUE TITLE
Error 242 - Сумма слишком велика - Amount is huge

### ISSUE THREAD

**Issue by garex** [QIWI-API/pull-payments-docs#3]
У кого узнать лимиты? У менеджера? Или они захардкожены где-то?

https://github.com/QIWI-API/pull-payments-docs/blame/6d55bdf918df21c9608f0527cb7822caff2f6201/_errors_ru.html.md#L17

**Comment by mmmikhail** [comment]
У каждого мерчанта своя макс.сумма счета, надо узнавать у менеджера
